var FaceTecStrings = {
  "FaceTec_accessibility_cancel_button": "Cancelar",

  "FaceTec_feedback_center_face": "Centralize Seu Rosto",
  "FaceTec_feedback_face_not_found": "Enquadre o Seu Rosto",
  "FaceTec_feedback_move_phone_away": "Afaste-se",
  "FaceTec_feedback_move_away_web": "Afaste-se",
  "FaceTec_feedback_move_phone_closer": "Aproxime-se",
  "FaceTec_feedback_move_phone_to_eye_level": "Telefone ao Nível dos Olhos",
  "FaceTec_feedback_move_to_eye_level_web": "Olhe Para a Câmera",
  "FaceTec_feedback_face_not_looking_straight_ahead": "Olhe Para Frente",
  "FaceTec_feedback_face_not_upright": "Mantenha a Cabeça Reta",
  "FaceTec_feedback_face_not_upright_mobile": "Mantenha a Cabeça Reta",
  "FaceTec_feedback_hold_steady": "Segure Firme",
  "FaceTec_feedback_move_web_closer": "Aproxime-se",
  "FaceTec_feedback_move_web_even_closer": "Mais Próximo",
  "FaceTec_feedback_use_even_lighting": "Ilumine Seu Rosto Uniformemente",

  "FaceTec_instructions_header_ready_desktop": "Prepare-se Para a Selfie",
  "FaceTec_instructions_header_ready_1_mobile": "Prepare-se",
  "FaceTec_instructions_header_ready_2_mobile": "Seu Vídeo Selfie",
  "FaceTec_instructions_message_ready_desktop": "Encaixe Seu Rosto no Espaço Oval, Clique Estou Pronto & Aproxime-se",
  "FaceTec_instructions_message_ready_1_mobile": "Encaixe Seu Rosto no Espaço Oval,",
  "FaceTec_instructions_message_ready_2_mobile": "Clique Estou Pronto & Aproxime-se",

  "FaceTec_action_im_ready": "ESTOU PRONTO",
  "FaceTec_presession_frame_your_face": "Encaixe Seu Rosto no Espaço Oval",
  "FaceTec_presession_look_straight_ahead": "Olhe Para Frente",
  "FaceTec_presession_hold_steady3": "Aguente Firme: 3",
  "FaceTec_presession_hold_steady2": "Aguente Firme: 2",
  "FaceTec_presession_hold_steady1": "Aguente Firme: 1",
  "FaceTec_presession_eyes_straight_ahead": "Olhe Para Frente",
  "FaceTec_presession_remove_dark_glasses": "Tire Seus Óculos de Sol",
  "FaceTec_presession_neutral_expression": "Fique Neutro, Não Sorria",
  "FaceTec_presession_conditions_too_bright": "Ambiente Muito Iluminado",
  "FaceTec_presession_brighten_your_environment": "Ambiente Muito Escuro",

  "FaceTec_result_facescan_upload_message": "Upload<br/>Criptografado<br/>do Liveness 3D",
  "FaceTec_result_idscan_upload_message": "Upload<br/>Criptografado<br/>do Documento",

  "FaceTec_retry_header": "Tentar Novamente",
  "FaceTec_retry_subheader_message": "Dê uma olhada nas suas imagens e corrija o seu ambiente.",
  "FaceTec_retry_your_image_label": "Sua Selfie",
  "FaceTec_retry_ideal_image_label": "Pose Ideal",
  "FaceTec_retry_instruction_message_1": "Expressão Neutra, Sem Sorrir",
  "FaceTec_retry_instruction_message_2": "Sem Reflexo ou Iluminação Extrema",
  "FaceTec_retry_instruction_message_3": "Muito Borrado, Limpe Sua Câmera",
  "FaceTec_action_try_again": "TENTE NOVAMENTE",

  "FaceTec_camera_feed_issue_header": "<b>Problemas Para Criptografar o Conteúdo da Câmera</b>",
  "FaceTec_camera_feed_issue_subheader_message": "Esse sistema não pode ser verificado:",
  "FaceTec_camera_feed_issue_table_header_1": "Possível Erro",
  "FaceTec_camera_feed_issue_table_header_2": "Corrigir",
  "FaceTec_camera_feed_issue_table_row_1_cell_1_firefox_permissions_error": "Permissões da Câmera Não Lembrada Pelo Firefox.",
  "FaceTec_camera_feed_issue_table_row_1_cell_2_firefox_permissions_error": "Permissões da Câmera Verificadas.",
  "FaceTec_camera_feed_issue_table_row_1_cell_1": "Câmera em uso por outro aplicativo.",
  "FaceTec_camera_feed_issue_table_row_1_cell_2": "Feche outros aplicativos.",
  "FaceTec_camera_feed_issue_table_row_2_cell_1": "Um aplicativo de terceiros está modificando o vídeo.",
  "FaceTec_camera_feed_issue_table_row_2_cell_2": "Feche/Desinstale o outro aplicativo.",
  "FaceTec_camera_feed_issue_table_row_3_cell_1": "O dispositivo não é seguro.",
  "FaceTec_camera_feed_issue_table_row_3_cell_2": "Use um dispositivo diferente.",
  "FaceTec_camera_feed_issue_subtable_message": "Este aplicativo bloqueia configurações suspeitas de Webcam. <a href='https://livenesscheckhelp.com/' target='_blank' style='text-decoration:underline;'>Saiba Mais</a>.",
  "FaceTec_camera_feed_issue_action": "Tente Novamente",
  "FaceTec_camera_feed_issue_action_firefox_permissions_error": "OK",

  "FaceTec_camera_permission_header": "Ativar Câmera",
  "FaceTec_camera_permission_message": "O acesso à câmera está desativado. Toque abaixo para ativar em ajustes.",
  "FaceTec_action_ok": "OK",

  "FaceTec_enter_fullscreen_header": "Selfie Modo Tela Cheia",
  "FaceTec_enter_fullscreen_message": "Antes de começar, clique no botão abaixo para abrir o modo tela cheia",
  "FaceTec_enter_fullscreen_action": "Abrir Tela Cheia",

  "FaceTec_initializing_camera": "Iniciando a Câmera...",
  "FaceTec_initializing_camera_still_loading": "Criptografando o Conteúdo da Câmera...",

  "FaceTec_idscan_type_selection_header": "Tipo do Documento",
  "FaceTec_action_select_id_card": "Documento Com Foto",
  "FaceTec_action_select_passport": "PASSAPORTE",
  "FaceTec_idscan_capture_id_card_front_instruction_message": "Mostre a Frente do Documento Com Foto",
  "FaceTec_idscan_capture_id_card_back_instruction_message": "Mostre o Verso do Documento",
  "FaceTec_idscan_capture_passport_instruction_message": "Mostre a Página da Foto no Passaporte",
  "FaceTec_action_take_photo": "TIRAR FOTO",
  "FaceTec_idscan_review_id_card_front_instruction_message": "Confirme Se a Foto Está Clara e Legível",
  "FaceTec_idscan_review_id_card_back_instruction_message": "Confirme Se Está Claro e Legível",
  "FaceTec_idscan_review_passport_instruction_message": "Confirme Se a Foto Está Clara e Legível",
  "FaceTec_action_accept_photo": "ACEITAR",
  "FaceTec_action_retake_photo": "RECAPTURAR",

  "FaceTec_result_idscan_unsuccess_message": "Foto do Documento Nāo Corresponde com Rosto do Usuário",

  "FaceTec_result_success_message": "Sucesso!"
};

module.exports = FaceTecStrings;
