import { FaceCaptcha } from '@oiti/facecaptcha-core';
import axios from 'axios';
import { FaceTecSDK } from '../../core/core-sdk/FaceTecSDK.js/FaceTecSDK';
import { ThemeHelpers } from '../../core/utilities/ThemeHelpers';
import { LivenessCheckProcessor } from '../../core/processor/LivenessCheckProcessor';
import { Config } from '../Config';
import { SampleAppUtilities } from '../../core/utilities/SampleAppUtilities';
import * as FaceTecStringsPtBr from '../../core/core-sdk-optional/FaceTecStrings.pt-br';

export var SampleApp = (function () {
  let resultProductKey = '';
  let resultSessionToken = '';

  let latestEnrollmentIdentifier = '';
  let latestSessionResult = null;
  let latestIDScanResult = null;
  let latestProcessor;

  const status = 'Inicializando...';
  const deviceKeyIdentifier = 'dF2CabwQ6OCLFJaV2QqZhP7OUErHv0uz';
  const publicFaceScanEncryptionKey =
    '-----BEGIN PUBLIC KEY-----\n' +
    'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5PxZ3DLj+zP6T6HFgzzk\n' +
    'M77LdzP3fojBoLasw7EfzvLMnJNUlyRb5m8e5QyyJxI+wRjsALHvFgLzGwxM8ehz\n' +
    'DqqBZed+f4w33GgQXFZOS4AOvyPbALgCYoLehigLAbbCNTkeY5RDcmmSI/sbp+s6\n' +
    'mAiAKKvCdIqe17bltZ/rfEoL3gPKEfLXeN549LTj3XBp0hvG4loQ6eC1E1tRzSkf\n' +
    'GJD4GIVvR+j12gXAaftj3ahfYxioBH7F7HQxzmWkwDyn3bqU54eaiB7f0ftsPpWM\n' +
    'ceUaqkL2DZUvgN0efEJjnWy5y1/Gkq5GGWCROI9XG/SwXJ30BbVUehTbVcD70+ZF\n' +
    '8QIDAQAB\n' +
    '-----END PUBLIC KEY-----';

  let userAgent = null;

  const getUserAgent = () => {
    if (userAgent === null) {
      userAgent = FaceTecSDK.createFaceTecAPIUserAgentString('');
    }

    return userAgent;
  };

  let teardown = Promise.resolve();

  let initialized = false;
  let initializing = false;

  const loadAssets = () => {
    if (initialized || initializing) {
      SampleAppUtilities.enableControlButtons();

      return;
    }

    initializing = true;

    // Defina um caminho de diretório para outros recursos do FaceTec Browser SDK.
    FaceTecSDK.setResourceDirectory(
      '../../core/core-sdk/FaceTecSDK.js/resources'
    );

    // Defina o caminho do diretório para as imagens necessárias do FaceTec Browser SDK.
    FaceTecSDK.setImagesDirectory('../../core/core-sdk/FaceTec_images');

    // Defina as personalizações do FaceTec Device SDK.
    ThemeHelpers.setAppTheme(ThemeHelpers.getCurrentTheme());

    // Inicialize o FaceTec Browser SDK e configure os recursos da interface do
    // usuário.
    Config.initializeFromAutogeneratedConfig(
      FaceTecSDK,
      function (initializedSuccessfully) {
        initializing = false;
        initialized = initializedSuccessfully;

        if (initializedSuccessfully) {
          SampleAppUtilities.enableControlButtons();

          // Set localization
          FaceTecSDK.configureLocalization(FaceTecStringsPtBr);
        }

        SampleAppUtilities.displayStatus(
          FaceTecSDK.getFriendlyDescriptionForFaceTecSDKStatus(
            FaceTecSDK.getStatus()
          )
        );
      },
      resultProductKey,
      deviceKeyIdentifier,
      publicFaceScanEncryptionKey
    );

    SampleAppUtilities.formatUIForDevice();
  };

  const getProductionKey = async () => {
    await teardown;

    const facecaptchaService = new FaceCaptcha(axios, {
      BaseURL: process.env.REACT_APP_BASE_URL,
    });

    const result = await facecaptchaService.getProductionKey({
      appKey: window.localStorage.getItem('appkey')
    });

    if (result.productionKey) {
      resultProductKey = result.productionKey;

      loadAssets();
    } else {
      SampleAppUtilities.displayStatus(
        'Sua appkey é inválida. Por favor, retorne para a home clicando no link no final da tela.'
      );
    }
  };

  const getSessionToken = async () => {
    const facecaptchaService = new FaceCaptcha(axios, {
      BaseURL: process.env.REACT_APP_BASE_URL,
      timeout: 20000,
    });

    const result = await facecaptchaService.getSessionToken({
      appkey: window.localStorage.getItem('appkey'),
      userAgent: getUserAgent(),
    });

    resultSessionToken = result.sessionToken;

    window.localStorage.setItem('hasLiveness', 'true');

    // Obtenha um token de sessão do FaceTec SDK e inicie o 3D Liveness Check.
    latestProcessor = new LivenessCheckProcessor(resultSessionToken, SampleApp);
  };

  // Inicie um 3D Liveness Check.
  const onLivenessCheckPressed = () => {
    SampleAppUtilities.fadeOutMainUIAndPrepareForSession();

    getSessionToken();
  };

  const onComplete = () => {
    if (!latestProcessor) {
      return;
    }

    SampleAppUtilities.showMainUI();

    if (!latestProcessor.isSuccess()) {
      // Redefina o identificador de inscrição.
      latestEnrollmentIdentifier = '';

      return;
    }

    // Mostrar mensagem de sucesso na tela
    SampleAppUtilities.displayStatus('Enviado com sucesso');
  };

  const reset = () => {
    if (latestProcessor) {
      latestProcessor.latestNetworkRequest.abort();
    }

    resultProductKey = '';
    resultSessionToken = '';
    latestEnrollmentIdentifier = '';
    latestSessionResult = null;
    latestIDScanResult = null;
    latestProcessor = null;
    userAgent = null;
    initialized = false;
    initializing = false;

    teardown = teardown.then(deinitialize);
  };

  const deinitialize = () => {
    return new Promise((resolve) => {
      if (typeof FaceTecSDK.deinitialize !== 'function') {
        resolve();

        return;
      }

      try {
        FaceTecSDK.deinitialize(() => resolve());
      } catch (e) {
        console.warn('FaceTec deinitialize falhou', e);

        resolve();
      }
    });
  };

  const setLatestSessionResult = (sessionResult) => {
    latestSessionResult = sessionResult;
  };

  const setIDScanResult = (idScanResult) => {
    latestIDScanResult = idScanResult;
  };

  const getLatestEnrollmentIdentifier = () => {
    return latestEnrollmentIdentifier;
  };

  const setLatestServerResult = (responseJSON) => {};

  const getAppKey = () => {
    return window.localStorage.getItem('appkey');
  };

  return {
    status,
    getProductionKey,
    reset,
    onLivenessCheckPressed,
    onComplete,
    setLatestSessionResult,
    setIDScanResult,
    getLatestEnrollmentIdentifier,
    setLatestServerResult,
    getAppKey,
  };
})();
